# Generated by Django 3.2.1 on 2021-05-06 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmpInfo', '0002_thana'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thana',
            old_name='thana',
            new_name='district',
        ),
    ]
