# Generated by Django 3.2.1 on 2021-05-06 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EmpInfo', '0004_department_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thana',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='district', to='EmpInfo.district'),
        ),
    ]
