# Generated by Django 3.2.1 on 2021-05-06 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EmpInfo', '0005_alter_thana_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpBasicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('joiningdate', models.DateField()),
                ('status', models.CharField(choices=[('Permanent', 'Permanent'), ('Trainee', 'Trainee')], max_length=15)),
                ('remarks', models.TextField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmpInfo.department')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmpInfo.designation')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmpInfo.district')),
                ('thana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmpInfo.thana')),
            ],
        ),
        migrations.CreateModel(
            name='EmpSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basicsalary', models.FloatField()),
                ('medical', models.FloatField()),
                ('houserent', models.FloatField()),
                ('others', models.FloatField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmpInfo.empbasicinfo')),
            ],
        ),
        migrations.CreateModel(
            name='EmpEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(choices=[('SSC', 'SSC'), ('HSC', 'HSC'), ('Bachelor', 'Bachelor')], max_length=10)),
                ('institute', models.CharField(max_length=100)),
                ('passingyear', models.IntegerField()),
                ('result', models.CharField(max_length=5)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmpInfo.empbasicinfo')),
            ],
        ),
    ]
