# Generated by Django 3.2.1 on 2021-05-06 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpInfo', '0006_empbasicinfo_empeducation_empsalary'),
    ]

    operations = [
        migrations.AddField(
            model_name='empbasicinfo',
            name='image',
            field=models.ImageField(null=True, upload_to='emp_images'),
        ),
    ]
