# Generated by Django 3.2.1 on 2021-05-08 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpInfo', '0007_empbasicinfo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='empbasicinfo',
            name='emp_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
