# Generated by Django 3.2.1 on 2021-05-08 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmpInfo', '0009_alter_empbasicinfo_emp_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empbasicinfo',
            name='emp_id',
        ),
    ]
