# Generated by Django 3.2.1 on 2021-05-08 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpInfo', '0010_remove_empbasicinfo_emp_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='empbasicinfo',
            name='emp_id',
            field=models.CharField(default='1111', max_length=10, unique=True),
        ),
    ]
