# Generated by Django 3.2.1 on 2021-05-08 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpInfo', '0011_empbasicinfo_emp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empbasicinfo',
            name='emp_id',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
