# Generated by Django 3.2.1 on 2021-05-17 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpInfo', '0014_alter_empbasicinfo_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empbasicinfo',
            name='emp_id',
            field=models.CharField(db_column='emp_id', db_index=True, max_length=15, null=True, unique=True),
        ),
    ]
