# Generated by Django 3.2.1 on 2021-10-22 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EmpInfo', '0015_alter_empbasicinfo_emp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thana',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='district', related_query_name='tag', to='EmpInfo.district'),
        ),
    ]
