# Generated by Django 3.2.1 on 2021-10-23 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpInfo', '0017_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suit', models.IntegerField(choices=[(1, 'Diamond'), (2, 'Spade'), (3, 'Heart'), (4, 'Club')])),
            ],
        ),
    ]
