# Generated by Django 3.2.1 on 2021-11-06 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EmpInfo', '0023_alter_entry_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog', related_query_name='tag', to='EmpInfo.blog'),
        ),
    ]
